version: '3.9'

services:
  vidslide-api:
    build:
      dockerfile: Dockerfile
      context: ./
    image: jonasfroeller/vidslide-backend:latest
    restart: always
    ports:
      - "8196:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/media:/var/lib/store
  vidslide-db:
    image: mysql:8.0.32
    command: --authentication_policy=mysql_native_password 
    restart: always
    ports:
      - "3196:3306"
    volumes:
      - /var/lib/vidslide_database:/var/lib/mysql # don't forget to change this bind-mount path to fit your preferences!
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # set (Windows) | export (Linux) in commandline || env_file: database.env

# INFO:
# If you are using Windows and want to save the files in WSL2: navigate to folder => cd /mnt/<disk_name>/<path> && sudo docker-compose up --build -d
# LOGIN the "vidslide-db" database in the container console: mysql -u root -p <schema> (asks for password set in vidslide-db.environment.MYSQL_ROOT_PASSWORD)