version: '3.8'

services:
  vidslide-api:
    build:
      dockerfile: Dockerfile
      context: ./
    image: vidslide-api-php:8.1.17-apache
    restart: always
    ports:
      - "8196:80"
    volumes:
      - ./backend:/var/www/html
  vidslide-db:
    image: mysql:8.0.32
    command: --authentication_policy=mysql_native_password 
    restart: always
    ports:
      - "3196:3306"
    volumes:
      - /var/lib/vidslidedb:/var/lib/mysql # change /var/lib/vidslidedb to other path if WSL2 is not installed and windows is your OS

# INFO:   
# set in docker-compose file: vidslide-db.environment.MYSQL_ROOT_PASSWORD: <password> || set in build command
# RUN ON LINUX for the bind-mount to work with WSL2 path (navigate to folder: /mnt/disk/<path>): sudo MYSQL_ROOT_PASSWORD=<password> docker-compose up --build -d
# LOGIN DATABASE ON CONTAINER: mysql -u root -p <schema> => asks for password set in vidslide-db.environment.MYSQL_ROOT_PASSWORD