version: '3.9'

services:
  vidslide-api:
    build:
      dockerfile: Dockerfile
      context: ./
    image: php:8.1.17-apache
    restart: always
    ports:
      - "8196:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/media:/var/lib/store
  vidslide-db:
    image: mysql:8.0.32
    command: --authentication_policy=mysql_native_password 
    restart: always
    ports:
      - "3196:3306"
    volumes:
      - /var/lib/vidslide_database:/var/lib/mysql # /var/lib/vidslide_database:/var/lib/mysql # change /var/lib/vidslidedb to other path if WSL2 is not installed and windows is your OS
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # || env_file: database.env

# INFO:
# RUN ON LINUX for the bind-mount to work with WSL2 path (navigate to folder: /mnt/disk/<path>): sudo docker-compose up --build -d
# LOGIN DATABASE ON CONTAINER: mysql -u root -p <schema> => asks for password set in vidslide-db.environment.MYSQL_ROOT_PASSWORD

#  alternative to ./backend/media
#  vidslide-media:
#    image: busybox:1.34.1-glibc
#    command: tail -f /dev/null
#    restart: always
#    volumes:
#      - /var/lib/vidslide_storage:/data